# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashbord9.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ParentalControle(object):
    def setupUi(self, ParentalControle):
        ParentalControle.setObjectName("ParentalControle")
        ParentalControle.resize(992, 500)
        ParentalControle.setMinimumSize(QtCore.QSize(0, 500))
        ParentalControle.setLayoutDirection(QtCore.Qt.LeftToRight)
        ParentalControle.setAutoFillBackground(False)
        ParentalControle.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.centralwidget = QtWidgets.QWidget(ParentalControle)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Top_Bar = QtWidgets.QFrame(self.centralwidget)
        self.Top_Bar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.Top_Bar.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.Top_Bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Top_Bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Top_Bar.setObjectName("Top_Bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Top_Bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout.addWidget(self.Top_Bar)
        self.Content = QtWidgets.QFrame(self.centralwidget)
        self.Content.setMinimumSize(QtCore.QSize(0, 0))
        self.Content.setStyleSheet("background-image:rgb(0, 255, 127)")
        self.Content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Content.setObjectName("Content")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Content)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_left_menu = QtWidgets.QFrame(self.Content)
        self.frame_left_menu.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_left_menu.setMaximumSize(QtCore.QSize(70, 16777215))
        self.frame_left_menu.setStyleSheet("\n"
"background-color: rgb(44, 49, 60);")
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_5 = QtWidgets.QFrame(self.frame_left_menu)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_2.addWidget(self.frame_5)
        self.label_8 = QtWidgets.QLabel(self.frame_left_menu)
        self.label_8.setMaximumSize(QtCore.QSize(100, 100))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("image.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setWordWrap(False)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8, 0, QtCore.Qt.AlignHCenter)
        self.frame_top_menus = QtWidgets.QFrame(self.frame_left_menu)
        self.frame_top_menus.setStyleSheet("background-image:rgb(0, 255, 127)")
        self.frame_top_menus.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_menus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_menus.setObjectName("frame_top_menus")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_top_menus)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_page_1 = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_page_1.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_page_1.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(44, 49, 60);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    \n"
"    \n"
"    background-color: rgb(52, 59, 72);\n"
"    \n"
"}\n"
"")
        self.btn_page_1.setObjectName("btn_page_1")
        self.verticalLayout_4.addWidget(self.btn_page_1)
        self.btn_page_2 = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_page_2.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_page_2.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(44, 49, 60);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(52, 59, 72);\n"
"}")
        self.btn_page_2.setObjectName("btn_page_2")
        self.verticalLayout_4.addWidget(self.btn_page_2)
        self.btn_page_3 = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_page_3.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_page_3.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(44, 49, 60);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(52, 59, 72);\n"
"}")
        self.btn_page_3.setObjectName("btn_page_3")
        self.verticalLayout_4.addWidget(self.btn_page_3)
        self.verticalLayout_2.addWidget(self.frame_top_menus, 0, QtCore.Qt.AlignVCenter)
        self.frame_6 = QtWidgets.QFrame(self.frame_left_menu)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_2.addWidget(self.frame_6)
        self.horizontalLayout_2.addWidget(self.frame_left_menu)
        self.frame_pages = QtWidgets.QFrame(self.Content)
        self.frame_pages.setStyleSheet("\n"
"background-color: rgb(52, 59, 72);")
        self.frame_pages.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pages.setObjectName("frame_pages")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_pages)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_pages)
        self.stackedWidget.setStyleSheet("\n"
"background-color: rgb(52, 59, 72);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame = QtWidgets.QFrame(self.page_1)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frameglobale = QtWidgets.QFrame(self.frame)
        self.frameglobale.setMinimumSize(QtCore.QSize(400, 0))
        self.frameglobale.setSizeIncrement(QtCore.QSize(300, 300))
        self.frameglobale.setStyleSheet("QFrame{\n"
"    background-color: rgb(85, 255, 255)\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(1, 90, 153);\n"
"}\n"
"QLineEdit {\n"
"    border: 2px solid rgb(0, 93, 159);\n"
"    border-radius: 10px;\n"
"    padding: 15px;\n"
"    background-color: rgb(0, 69, 116);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(0, 66, 124);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(206, 206, 206);\n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"QPushButton {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 10px;\n"
"    padding: 15px;\n"
"    background-color:rgb(14, 13, 24);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(0, 66, 124);\n"
"}\n"
"QLabel{\n"
"    border:3px solid  rgb(45, 45, 45);\n"
"    border-radius: 10px;\n"
"    \n"
"    background-color: rgb(6, 63, 104);\n"
"}\n"
"QCheckBox{\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 10px;\n"
"}\n"
"QCheckBox::indicator {\n"
"    border: 3px solid rgb(0, 93, 159);\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border-radius: 10px;\n"
"    background:rgb(0, 0, 0);\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 3px solid rgb(255, 255, 255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background: 3px solid rgb(34, 34, 34);\n"
"    \n"
"}\n"
"")
        self.frameglobale.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameglobale.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameglobale.setObjectName("frameglobale")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frameglobale)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_icon = QtWidgets.QFrame(self.frameglobale)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.frame_icon.setFont(font)
        self.frame_icon.setStyleSheet("\n"
"background-color: rgb(52, 59, 72);\n"
"color: rgb(255, 255, 255);")
        self.frame_icon.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_icon.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_icon.setObjectName("frame_icon")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_icon)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_3 = QtWidgets.QLabel(self.frame_icon)
        self.label_3.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("\n"
"background-color: rgb(52, 59, 72);")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_8.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_10.addWidget(self.frame_icon)
        self.infolabeltext = QtWidgets.QFrame(self.frameglobale)
        self.infolabeltext.setStyleSheet("\n"
"background-color: rgb(52, 59, 72);\n"
"\n"
"color: rgb(255, 255, 255);")
        self.infolabeltext.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.infolabeltext.setFrameShadow(QtWidgets.QFrame.Raised)
        self.infolabeltext.setObjectName("infolabeltext")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.infolabeltext)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.infolebel = QtWidgets.QFrame(self.infolabeltext)
        self.infolebel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.infolebel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.infolebel.setObjectName("infolebel")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.infolebel)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.emaillabel = QtWidgets.QLabel(self.infolebel)
        self.emaillabel.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.emaillabel.setFont(font)
        self.emaillabel.setStyleSheet("")
        self.emaillabel.setAlignment(QtCore.Qt.AlignCenter)
        self.emaillabel.setObjectName("emaillabel")
        self.verticalLayout_11.addWidget(self.emaillabel)
        self.passwordlabel = QtWidgets.QLabel(self.infolebel)
        self.passwordlabel.setMinimumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.passwordlabel.setFont(font)
        self.passwordlabel.setStyleSheet("")
        self.passwordlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.passwordlabel.setObjectName("passwordlabel")
        self.verticalLayout_11.addWidget(self.passwordlabel)
        self.horizontalLayout_6.addWidget(self.infolebel)
        self.infotext = QtWidgets.QFrame(self.infolabeltext)
        self.infotext.setStyleSheet("\n"
"background-color: rgb(52, 59, 72);")
        self.infotext.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.infotext.setFrameShadow(QtWidgets.QFrame.Raised)
        self.infotext.setObjectName("infotext")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.infotext)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.emailtext = QtWidgets.QLineEdit(self.infotext)
        self.emailtext.setMinimumSize(QtCore.QSize(200, 50))
        self.emailtext.setMaximumSize(QtCore.QSize(200, 16777215))
        self.emailtext.setStyleSheet("border:3px solid  ;\n"
"border-left-color: rgb(52, 59, 72);\n"
"border-right-color: rgb(52, 59, 72);\n"
"border-top-color: rgb(52, 59, 72);\n"
"border-bottom-color: rgb(44, 49, 60);")
        self.emailtext.setAlignment(QtCore.Qt.AlignCenter)
        self.emailtext.setObjectName("emailtext")
        self.verticalLayout_12.addWidget(self.emailtext)
        self.passwordtest = QtWidgets.QLineEdit(self.infotext)
        self.passwordtest.setMinimumSize(QtCore.QSize(200, 50))
        self.passwordtest.setMaximumSize(QtCore.QSize(200, 16777215))
        self.passwordtest.setStyleSheet("border:3px solid  ;\n"
"border-left-color: rgb(52, 59, 72);\n"
"border-right-color: rgb(52, 59, 72);\n"
"border-top-color: rgb(52, 59, 72);\n"
"border-bottom-color: rgb(44, 49, 60);\n"
"")
        self.passwordtest.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordtest.setAlignment(QtCore.Qt.AlignCenter)
        self.passwordtest.setObjectName("passwordtest")
        self.verticalLayout_12.addWidget(self.passwordtest)
        self.horizontalLayout_6.addWidget(self.infotext, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_10.addWidget(self.infolabeltext)
        self.login_btn = QtWidgets.QPushButton(self.frameglobale)
        self.login_btn.setMinimumSize(QtCore.QSize(200, 10))
        self.login_btn.setMaximumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.login_btn.setFont(font)
        self.login_btn.setStyleSheet("\n"
"QPushButton {\n"
"border:3px solid  rgb(44, 49, 60);\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(44, 49, 60);\n"
"}\n"
"QPushButton:hover {\n"
"    border:3px solid ;\n"
"    \n"
"    \n"
"    border-color: rgb(67, 72, 88);\n"
"    background-color: rgb(67, 72, 88);\n"
"}\n"
"")
        self.login_btn.setObjectName("login_btn")
        self.verticalLayout_10.addWidget(self.login_btn, 0, QtCore.Qt.AlignHCenter)
        self.butonsloginepage = QtWidgets.QFrame(self.frameglobale)
        self.butonsloginepage.setMinimumSize(QtCore.QSize(50, 90))
        self.butonsloginepage.setMaximumSize(QtCore.QSize(300, 300))
        self.butonsloginepage.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.butonsloginepage.setFrameShadow(QtWidgets.QFrame.Raised)
        self.butonsloginepage.setObjectName("butonsloginepage")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.butonsloginepage)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_10.addWidget(self.butonsloginepage)
        self.subbottonloginpage = QtWidgets.QFrame(self.frameglobale)
        self.subbottonloginpage.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.subbottonloginpage.setFrameShadow(QtWidgets.QFrame.Raised)
        self.subbottonloginpage.setObjectName("subbottonloginpage")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.subbottonloginpage)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_10.addWidget(self.subbottonloginpage, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_9.addWidget(self.frameglobale)
        self.verticalLayout_7.addWidget(self.frame)
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frameglobale_2 = QtWidgets.QFrame(self.page_2)
        self.frameglobale_2.setMinimumSize(QtCore.QSize(400, 0))
        self.frameglobale_2.setSizeIncrement(QtCore.QSize(300, 300))
        self.frameglobale_2.setStyleSheet("QFrame{\n"
"    background-color: rgb(86, 86, 86);\n"
"    background-color: rgb(85, 255, 255)\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(1, 90, 153);\n"
"}\n"
"QLineEdit {\n"
"    border: 2px solid rgb(0, 93, 159);\n"
"    border-radius: 10px;\n"
"    padding: 15px;\n"
"    background-color: rgb(0, 69, 116);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(0, 66, 124);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(206, 206, 206);\n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"QPushButton {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 10px;\n"
"    padding: 15px;\n"
"    background-color:rgb(14, 13, 24);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(0, 66, 124);\n"
"}\n"
"QLabel{\n"
"    border:3px solid  rgb(45, 45, 45);\n"
"    border-radius: 10px;\n"
"    \n"
"    background-color: rgb(6, 63, 104);\n"
"}\n"
"QCheckBox{\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 10px;\n"
"}\n"
"QCheckBox::indicator {\n"
"    border: 3px solid rgb(0, 93, 159);\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border-radius: 10px;\n"
"    background:rgb(0, 0, 0);\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 3px solid rgb(255, 255, 255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background: 3px solid rgb(34, 34, 34);\n"
"\n"
"}\n"
"")
        self.frameglobale_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameglobale_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameglobale_2.setObjectName("frameglobale_2")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frameglobale_2)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_icon_2 = QtWidgets.QFrame(self.frameglobale_2)
        self.frame_icon_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_icon_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_icon_2.setObjectName("frame_icon_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_icon_2)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_2 = QtWidgets.QLabel(self.frame_icon_2)
        self.label_2.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(52, 59, 72);")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_9.addWidget(self.label_2)
        self.verticalLayout_14.addWidget(self.frame_icon_2)
        self.infolabeltext_2 = QtWidgets.QFrame(self.frameglobale_2)
        self.infolabeltext_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.infolabeltext_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.infolabeltext_2.setObjectName("infolabeltext_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.infolabeltext_2)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.infolebel_2 = QtWidgets.QFrame(self.infolabeltext_2)
        self.infolebel_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.infolebel_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.infolebel_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.infolebel_2.setObjectName("infolebel_2")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.infolebel_2)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.emaillabel_2 = QtWidgets.QLabel(self.infolebel_2)
        self.emaillabel_2.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.emaillabel_2.setFont(font)
        self.emaillabel_2.setStyleSheet("")
        self.emaillabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.emaillabel_2.setObjectName("emaillabel_2")
        self.verticalLayout_15.addWidget(self.emaillabel_2)
        self.passwordlabel_2 = QtWidgets.QLabel(self.infolebel_2)
        self.passwordlabel_2.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.passwordlabel_2.setFont(font)
        self.passwordlabel_2.setStyleSheet("")
        self.passwordlabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.passwordlabel_2.setObjectName("passwordlabel_2")
        self.verticalLayout_15.addWidget(self.passwordlabel_2)
        self.horizontalLayout_10.addWidget(self.infolebel_2)
        self.infotext_2 = QtWidgets.QFrame(self.infolabeltext_2)
        self.infotext_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.infotext_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.infotext_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.infotext_2.setObjectName("infotext_2")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.infotext_2)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.registeremailtext = QtWidgets.QLineEdit(self.infotext_2)
        self.registeremailtext.setMinimumSize(QtCore.QSize(200, 50))
        self.registeremailtext.setMaximumSize(QtCore.QSize(200, 16777215))
        self.registeremailtext.setStyleSheet("border:3px solid  ;\n"
"border-left-color: rgb(52, 59, 72);\n"
"border-right-color: rgb(52, 59, 72);\n"
"border-top-color: rgb(52, 59, 72);\n"
"border-bottom-color: rgb(44, 49, 60);")
        self.registeremailtext.setAlignment(QtCore.Qt.AlignCenter)
        self.registeremailtext.setObjectName("registeremailtext")
        self.verticalLayout_16.addWidget(self.registeremailtext, 0, QtCore.Qt.AlignHCenter)
        self.registerpasswordtest = QtWidgets.QLineEdit(self.infotext_2)
        self.registerpasswordtest.setMinimumSize(QtCore.QSize(200, 50))
        self.registerpasswordtest.setMaximumSize(QtCore.QSize(200, 16777215))
        self.registerpasswordtest.setStyleSheet("border:3px solid  ;\n"
"border-left-color: rgb(52, 59, 72);\n"
"border-right-color: rgb(52, 59, 72);\n"
"border-top-color: rgb(52, 59, 72);\n"
"border-bottom-color: rgb(44, 49, 60);")
        self.registerpasswordtest.setEchoMode(QtWidgets.QLineEdit.Password)
        self.registerpasswordtest.setAlignment(QtCore.Qt.AlignCenter)
        self.registerpasswordtest.setObjectName("registerpasswordtest")
        self.verticalLayout_16.addWidget(self.registerpasswordtest, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_10.addWidget(self.infotext_2)
        self.verticalLayout_14.addWidget(self.infolabeltext_2)
        self.subbottonloginpage_2 = QtWidgets.QFrame(self.frameglobale_2)
        self.subbottonloginpage_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.subbottonloginpage_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.subbottonloginpage_2.setObjectName("subbottonloginpage_2")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.subbottonloginpage_2)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.registerregister_btn = QtWidgets.QPushButton(self.subbottonloginpage_2)
        self.registerregister_btn.setMinimumSize(QtCore.QSize(100, 50))
        self.registerregister_btn.setMaximumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.registerregister_btn.setFont(font)
        self.registerregister_btn.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"border:3px solid  rgb(44, 49, 60);\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(44, 49, 60);\n"
"}\n"
"QPushButton:hover {\n"
"    border:3px solid ;\n"
"    \n"
"    \n"
"    border-color: rgb(67, 72, 88);\n"
"    background-color: rgb(67, 72, 88);\n"
"}\n"
"\n"
"")
        self.registerregister_btn.setObjectName("registerregister_btn")
        self.verticalLayout_17.addWidget(self.registerregister_btn, 0, QtCore.Qt.AlignHCenter)
        self.butonsloginepage_2 = QtWidgets.QFrame(self.subbottonloginpage_2)
        self.butonsloginepage_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.butonsloginepage_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.butonsloginepage_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.butonsloginepage_2.setObjectName("butonsloginepage_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.butonsloginepage_2)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_17.addWidget(self.butonsloginepage_2, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_14.addWidget(self.subbottonloginpage_2, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_6.addWidget(self.frameglobale_2)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.page_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.page_3)
        self.frame_2.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_2.setStyleSheet("background-color: rgb(44, 49, 60);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.ajouterfisbtn = QtWidgets.QPushButton(self.frame_3)
        self.ajouterfisbtn.setMinimumSize(QtCore.QSize(80, 0))
        self.ajouterfisbtn.setStyleSheet("\n"
"QPushButton {\n"
"\n"
"\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(44, 49, 60);\n"
"}\n"
"QPushButton:hover {\n"
"\n"
"    \n"
"    \n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"")
        self.ajouterfisbtn.setObjectName("ajouterfisbtn")
        self.verticalLayout_8.addWidget(self.ajouterfisbtn)
        self.listefilsbtn = QtWidgets.QPushButton(self.frame_3)
        self.listefilsbtn.setStyleSheet("\n"
"QPushButton {\n"
"\n"
"\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(44, 49, 60);\n"
"}\n"
"QPushButton:hover {\n"
"\n"
"    \n"
"background-color: rgb(52, 59, 72);\n"
"}\n"
"")
        self.listefilsbtn.setObjectName("listefilsbtn")
        self.verticalLayout_8.addWidget(self.listefilsbtn)
        self.webblockerbtn = QtWidgets.QPushButton(self.frame_3)
        self.webblockerbtn.setMinimumSize(QtCore.QSize(80, 0))
        self.webblockerbtn.setStyleSheet("\n"
"QPushButton {\n"
"\n"
"\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(44, 49, 60);\n"
"}\n"
"QPushButton:hover {\n"
"\n"
"    \n"
"    \n"
"background-color: rgb(52, 59, 72);\n"
"}\n"
"")
        self.webblockerbtn.setObjectName("webblockerbtn")
        self.verticalLayout_8.addWidget(self.webblockerbtn)
        self.listeblanchebtn = QtWidgets.QPushButton(self.frame_3)
        self.listeblanchebtn.setStyleSheet("\n"
"QPushButton {\n"
"\n"
"\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(44, 49, 60);\n"
"}\n"
"QPushButton:hover {\n"
"\n"
"    \n"
"    \n"
"background-color: rgb(52, 59, 72);\n"
"}\n"
"")
        self.listeblanchebtn.setObjectName("listeblanchebtn")
        self.verticalLayout_8.addWidget(self.listeblanchebtn)
        self.historiquebtn = QtWidgets.QPushButton(self.frame_3)
        self.historiquebtn.setStyleSheet("\n"
"QPushButton {\n"
"\n"
"\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(44, 49, 60);\n"
"}\n"
"QPushButton:hover {\n"
"\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"")
        self.historiquebtn.setObjectName("historiquebtn")
        self.verticalLayout_8.addWidget(self.historiquebtn)
        self.verticalLayout_18.addWidget(self.frame_3)
        self.horizontalLayout_3.addWidget(self.frame_2)
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.page_3)
        self.stackedWidget_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.ajouterfilspage = QtWidgets.QWidget()
        self.ajouterfilspage.setObjectName("ajouterfilspage")
        self.Nomfils = QtWidgets.QLabel(self.ajouterfilspage)
        self.Nomfils.setGeometry(QtCore.QRect(160, 130, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.Nomfils.setFont(font)
        self.Nomfils.setStyleSheet("color: rgb(255, 255, 255);")
        self.Nomfils.setObjectName("Nomfils")
        self.Prenomfils = QtWidgets.QLabel(self.ajouterfilspage)
        self.Prenomfils.setGeometry(QtCore.QRect(160, 200, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.Prenomfils.setFont(font)
        self.Prenomfils.setStyleSheet("color: rgb(255, 255, 255);")
        self.Prenomfils.setObjectName("Prenomfils")
        self.agefils = QtWidgets.QLabel(self.ajouterfilspage)
        self.agefils.setGeometry(QtCore.QRect(170, 270, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.agefils.setFont(font)
        self.agefils.setStyleSheet("color: rgb(255, 255, 255);")
        self.agefils.setObjectName("agefils")
        self.nomfilstext = QtWidgets.QLineEdit(self.ajouterfilspage)
        self.nomfilstext.setGeometry(QtCore.QRect(320, 130, 181, 31))
        self.nomfilstext.setStyleSheet("border:3px solid  ;\n"
"color: rgb(255, 255, 255);\n"
"border-left-color: rgb(52, 59, 72);\n"
"border-right-color: rgb(52, 59, 72);\n"
"border-top-color: rgb(52, 59, 72);\n"
"border-bottom-color: rgb(44, 49, 60);")
        self.nomfilstext.setObjectName("nomfilstext")
        self.prenomtext = QtWidgets.QLineEdit(self.ajouterfilspage)
        self.prenomtext.setGeometry(QtCore.QRect(320, 200, 181, 31))
        self.prenomtext.setStyleSheet("border:3px solid  ;\n"
"color: rgb(255, 255, 255);\n"
"border-left-color: rgb(52, 59, 72);\n"
"border-right-color: rgb(52, 59, 72);\n"
"border-top-color: rgb(52, 59, 72);\n"
"border-bottom-color: rgb(44, 49, 60);")
        self.prenomtext.setObjectName("prenomtext")
        self.agetext = QtWidgets.QLineEdit(self.ajouterfilspage)
        self.agetext.setGeometry(QtCore.QRect(330, 270, 181, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.agetext.setFont(font)
        self.agetext.setStyleSheet("border:3px solid  ;\n"
"color: rgb(255, 255, 255);\n"
"border-left-color: rgb(52, 59, 72);\n"
"border-right-color: rgb(52, 59, 72);\n"
"border-top-color: rgb(52, 59, 72);\n"
"border-bottom-color: rgb(44, 49, 60);")
        self.agetext.setObjectName("agetext")
        self.ajouterbtn = QtWidgets.QPushButton(self.ajouterfilspage)
        self.ajouterbtn.setGeometry(QtCore.QRect(240, 320, 100, 50))
        self.ajouterbtn.setMinimumSize(QtCore.QSize(100, 50))
        self.ajouterbtn.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ajouterbtn.setFont(font)
        self.ajouterbtn.setStyleSheet("\n"
"QPushButton {\n"
"border:3px solid  rgb(44, 49, 60);\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(44, 49, 60);\n"
"}\n"
"QPushButton:hover {\n"
"    border:3px solid ;\n"
"    \n"
"    \n"
"    border-color: rgb(67, 72, 88);\n"
"    background-color: rgb(67, 72, 88);\n"
"}\n"
"")
        self.ajouterbtn.setObjectName("ajouterbtn")
        self.label = QtWidgets.QLabel(self.ajouterfilspage)
        self.label.setGeometry(QtCore.QRect(100, 20, 471, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_9 = QtWidgets.QLabel(self.ajouterfilspage)
        self.label_9.setGeometry(QtCore.QRect(590, 40, 41, 21))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap(":/newPrefix/download.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.stackedWidget_2.addWidget(self.ajouterfilspage)
        self.Listefils = QtWidgets.QWidget()
        self.Listefils.setObjectName("Listefils")
        self.tableWidget = QtWidgets.QTableWidget(self.Listefils)
        self.tableWidget.setGeometry(QtCore.QRect(120, 110, 381, 321))
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.label_4 = QtWidgets.QLabel(self.Listefils)
        self.label_4.setGeometry(QtCore.QRect(230, 20, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.stackedWidget_2.addWidget(self.Listefils)
        self.Listeblanche = QtWidgets.QWidget()
        self.Listeblanche.setObjectName("Listeblanche")
        self.tablelisteblanche = QtWidgets.QTableWidget(self.Listeblanche)
        self.tablelisteblanche.setGeometry(QtCore.QRect(380, 120, 211, 321))
        self.tablelisteblanche.setColumnCount(1)
        self.tablelisteblanche.setObjectName("tablelisteblanche")
        self.tablelisteblanche.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablelisteblanche.setHorizontalHeaderItem(0, item)
        self.label_6 = QtWidgets.QLabel(self.Listeblanche)
        self.label_6.setGeometry(QtCore.QRect(180, 20, 261, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.definirurlblanche = QtWidgets.QLineEdit(self.Listeblanche)
        self.definirurlblanche.setGeometry(QtCore.QRect(130, 130, 191, 20))
        self.definirurlblanche.setStyleSheet("border:3px solid  ;\n"
"color: rgb(255, 255, 255);\n"
"border-left-color: rgb(52, 59, 72);\n"
"border-right-color: rgb(52, 59, 72);\n"
"border-top-color: rgb(52, 59, 72);\n"
"border-bottom-color: rgb(44, 49, 60);")
        self.definirurlblanche.setObjectName("definirurlblanche")
        self.urlblanche = QtWidgets.QLabel(self.Listeblanche)
        self.urlblanche.setGeometry(QtCore.QRect(30, 130, 81, 16))
        self.urlblanche.setStyleSheet("color: rgb(255, 255, 255);")
        self.urlblanche.setObjectName("urlblanche")
        self.urlblachebtn = QtWidgets.QPushButton(self.Listeblanche)
        self.urlblachebtn.setGeometry(QtCore.QRect(140, 240, 75, 23))
        self.urlblachebtn.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"border:3px solid  rgb(44, 49, 60);\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(44, 49, 60);\n"
"}\n"
"QPushButton:hover {\n"
"    border:3px solid ;\n"
"    \n"
"    \n"
"    border-color: rgb(67, 72, 88);\n"
"    background-color: rgb(67, 72, 88);\n"
"}\n"
"\n"
"")
        self.urlblachebtn.setObjectName("urlblachebtn")
        self.stackedWidget_2.addWidget(self.Listeblanche)
        self.Historique = QtWidgets.QWidget()
        self.Historique.setObjectName("Historique")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.Historique)
        self.tableWidget_3.setGeometry(QtCore.QRect(120, 80, 381, 321))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(2)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget_3.setHorizontalHeaderItem(2, item)
        self.label_7 = QtWidgets.QLabel(self.Historique)
        self.label_7.setGeometry(QtCore.QRect(210, 20, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.stackedWidget_2.addWidget(self.Historique)
        self.webblockerpage = QtWidgets.QWidget()
        self.webblockerpage.setObjectName("webblockerpage")
        self.url = QtWidgets.QLineEdit(self.webblockerpage)
        self.url.setGeometry(QtCore.QRect(30, 30, 131, 31))
        self.url.setStyleSheet("border:3px solid  ;\n"
"color: rgb(255, 255, 255);\n"
"border-left-color: rgb(52, 59, 72);\n"
"border-right-color: rgb(52, 59, 72);\n"
"border-top-color: rgb(52, 59, 72);\n"
"border-bottom-color: rgb(44, 49, 60);")
        self.url.setObjectName("url")
        self.pushButton = QtWidgets.QPushButton(self.webblockerpage)
        self.pushButton.setGeometry(QtCore.QRect(440, 20, 141, 41))
        self.pushButton.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"border:3px solid  rgb(44, 49, 60);\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(44, 49, 60);\n"
"}\n"
"QPushButton:hover {\n"
"    border:3px solid ;\n"
"    \n"
"    \n"
"    border-color: rgb(67, 72, 88);\n"
"    background-color: rgb(67, 72, 88);\n"
"}\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.webblockerpage)
        self.tableWidget_4.setGeometry(QtCore.QRect(10, 160, 381, 301))
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(3)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        self.date_d = QtWidgets.QLineEdit(self.webblockerpage)
        self.date_d.setGeometry(QtCore.QRect(190, 30, 91, 31))
        self.date_d.setStyleSheet("border:3px solid  ;\n"
"color: rgb(255, 255, 255);\n"
"border-left-color: rgb(52, 59, 72);\n"
"border-right-color: rgb(52, 59, 72);\n"
"border-top-color: rgb(52, 59, 72);\n"
"border-bottom-color: rgb(44, 49, 60);")
        self.date_d.setObjectName("date_d")
        self.date_f = QtWidgets.QLineEdit(self.webblockerpage)
        self.date_f.setGeometry(QtCore.QRect(320, 30, 81, 31))
        self.date_f.setStyleSheet("border:3px solid  ;\n"
"color: rgb(255, 255, 255);\n"
"border-left-color: rgb(52, 59, 72);\n"
"border-right-color: rgb(52, 59, 72);\n"
"border-top-color: rgb(52, 59, 72);\n"
"border-bottom-color: rgb(44, 49, 60);")
        self.date_f.setObjectName("date_f")
        self.label_5 = QtWidgets.QLabel(self.webblockerpage)
        self.label_5.setGeometry(QtCore.QRect(90, 90, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.lineEdit = QtWidgets.QLineEdit(self.webblockerpage)
        self.lineEdit.setGeometry(QtCore.QRect(400, 190, 151, 20))
        self.lineEdit.setStyleSheet("border:3px solid  ;\n"
"color: rgb(255, 255, 255);\n"
"border-left-color: rgb(52, 59, 72);\n"
"border-right-color: rgb(52, 59, 72);\n"
"border-top-color: rgb(52, 59, 72);\n"
"border-bottom-color: rgb(44, 49, 60);")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_2 = QtWidgets.QPushButton(self.webblockerpage)
        self.pushButton_2.setGeometry(QtCore.QRect(470, 250, 111, 41))
        self.pushButton_2.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"border:3px solid  rgb(44, 49, 60);\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(44, 49, 60);\n"
"}\n"
"QPushButton:hover {\n"
"    border:3px solid ;\n"
"    \n"
"    \n"
"    border-color: rgb(67, 72, 88);\n"
"    background-color: rgb(67, 72, 88);\n"
"}\n"
"\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.stackedWidget_2.addWidget(self.webblockerpage)
        self.horizontalLayout_3.addWidget(self.stackedWidget_2)
        self.stackedWidget.addWidget(self.page_3)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.horizontalLayout_2.addWidget(self.frame_pages)
        self.verticalLayout.addWidget(self.Content)
        ParentalControle.setCentralWidget(self.centralwidget)

        self.retranslateUi(ParentalControle)
        self.stackedWidget.setCurrentIndex(2)
        self.stackedWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ParentalControle)

    def retranslateUi(self, ParentalControle):
        _translate = QtCore.QCoreApplication.translate
        ParentalControle.setWindowTitle(_translate("ParentalControle", "MainWindow"))
        self.btn_page_1.setText(_translate("ParentalControle", "Login"))
        self.btn_page_2.setText(_translate("ParentalControle", "Register"))
        self.btn_page_3.setText(_translate("ParentalControle", "Menu"))
        self.label_3.setText(_translate("ParentalControle", "Login"))
        self.emaillabel.setText(_translate("ParentalControle", "Email"))
        self.passwordlabel.setText(_translate("ParentalControle", "Password"))
        self.emailtext.setPlaceholderText(_translate("ParentalControle", "Email"))
        self.passwordtest.setPlaceholderText(_translate("ParentalControle", "Password"))
        self.login_btn.setText(_translate("ParentalControle", "Login"))
        self.label_2.setText(_translate("ParentalControle", "                             Register"))
        self.emaillabel_2.setText(_translate("ParentalControle", "Email"))
        self.passwordlabel_2.setText(_translate("ParentalControle", "Password"))
        self.registeremailtext.setPlaceholderText(_translate("ParentalControle", "Email"))
        self.registerpasswordtest.setPlaceholderText(_translate("ParentalControle", "Password"))
        self.registerregister_btn.setText(_translate("ParentalControle", "Register "))
        self.ajouterfisbtn.setText(_translate("ParentalControle", "Ajouter fils"))
        self.listefilsbtn.setText(_translate("ParentalControle", "Liste fils"))
        self.webblockerbtn.setText(_translate("ParentalControle", "Liste noir"))
        self.listeblanchebtn.setText(_translate("ParentalControle", "Liste blanche"))
        self.historiquebtn.setText(_translate("ParentalControle", "Historique"))
        self.Nomfils.setText(_translate("ParentalControle", "Nom :"))
        self.Prenomfils.setText(_translate("ParentalControle", "Prenom :"))
        self.agefils.setText(_translate("ParentalControle", "Age :"))
        self.nomfilstext.setPlaceholderText(_translate("ParentalControle", "Nom"))
        self.prenomtext.setPlaceholderText(_translate("ParentalControle", "Prenom"))
        self.agetext.setPlaceholderText(_translate("ParentalControle", "Age"))
        self.ajouterbtn.setText(_translate("ParentalControle", "Ajouter"))
        self.label.setText(_translate("ParentalControle", "Ajouter Enfant/ Adolescent"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("ParentalControle", "Nom"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("ParentalControle", "Prenom"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("ParentalControle", "Age"))
        self.label_4.setText(_translate("ParentalControle", " Liste fils"))
        item = self.tablelisteblanche.horizontalHeaderItem(0)
        item.setText(_translate("ParentalControle", "Url"))
        self.label_6.setText(_translate("ParentalControle", "Liste blanche"))
        self.definirurlblanche.setPlaceholderText(_translate("ParentalControle", "Definir url"))
        self.urlblanche.setText(_translate("ParentalControle", "Url :"))
        self.urlblachebtn.setText(_translate("ParentalControle", "Ajouter Url"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("ParentalControle", "Nom"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("ParentalControle", "Url"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("ParentalControle", "Time"))
        self.label_7.setText(_translate("ParentalControle", "Historique"))
        self.url.setPlaceholderText(_translate("ParentalControle", "     www.Url.com"))
        self.pushButton.setText(_translate("ParentalControle", "Block site"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("ParentalControle", "Url"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("ParentalControle", "Date Debut"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("ParentalControle", "Date Fin"))
        self.date_d.setPlaceholderText(_translate("ParentalControle", "Date debut"))
        self.date_f.setPlaceholderText(_translate("ParentalControle", "Date fin"))
        self.label_5.setText(_translate("ParentalControle", "Liste noir"))
        self.lineEdit.setPlaceholderText(_translate("ParentalControle", "Mot Cle "))
        self.pushButton_2.setText(_translate("ParentalControle", "Ajouter mot cle"))

